<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AcroLap15" ignored="0" name="Cms_Eligibility_Test" tests="1" failures="1" timestamp="14 Dec 2017 13:49:38 GMT" time="101.482" errors="0">
  <testcase name="Cms_Eligibility_Test" time="95.266" classname="com.acams.ddf.testcases.Cms_Eligibility_Test">
    <failure type="java.lang.AssertionError" message="Test Case Failed catch black for t1 got executed">
      <![CDATA[java.lang.AssertionError: Test Case Failed catch black for t1 got executed
	at com.acams.ddf.base.BaseTest.reportFailure(BaseTest.java:681)
	at com.acams.ddf.testcases.Cms_Eligibility_Test.Cms_Eligibility_Test(Cms_Eligibility_Test.java:115)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Cms_Eligibility_Test -->
</testsuite> <!-- Cms_Eligibility_Test -->
